# Generated by Django 4.2.6 on 2023-10-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCSystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(max_length=255, unique=True)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('ram_total', models.FloatField()),
                ('ram_available', models.FloatField()),
                ('installed_apps', models.JSONField()),
            ],
        ),
    ]
